version: '3.8'

services:
  scenic-spot-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=your-production-jwt-secret-change-this
      - JWT_EXPIRES_IN=7d
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - MAX_FILE_SIZE=5242880
      - UPLOAD_PATH=uploads
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s