[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
NODE_ENV = "production"
PORT = "${{ PORT }}"

[environments.production.variables]
JWT_SECRET = "${{ JWT_SECRET }}"
JWT_EXPIRES_IN = "7d"
ADMIN_USERNAME = "${{ ADMIN_USERNAME }}"
ADMIN_PASSWORD = "${{ ADMIN_PASSWORD }}"
MAX_FILE_SIZE = "5242880"
UPLOAD_PATH = "uploads"
DATA_PATH = "data"
FRONTEND_URL = "${{ FRONTEND_URL }}"